# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('semilla', '0002_auto_20171108_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillapersona',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 22, 5, 41, 105380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='semillapersona',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 22, 5, 41, 105903, tzinfo=utc)),
        ),
    ]
